# this configuration file compiles the TemperBridge Nova firmware.
# use 'esphome compile temperbridge_nova.yaml' to build.

esphome:
  name: temperbridge-nova
  build_path: build/temperbridge_nova
  name_add_mac_suffix: true

packages:
  temperbridge_nova_base: !include packages/temperbridge_nova/base.yaml
  temperbridge_nova_model: !include packages/temperbridge_nova/cu358.yaml

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:

button:
  - platform: factory_reset
    id: factory_reset_button
    name: Restart with Factory Default Settings

binary_sensor:
  - platform: gpio
    id: improv_authorizer
    internal: true
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_click:
      min_length: 10000ms
      max_length: 30000ms
      then:
        - button.press: factory_reset_button

esp32_improv:
  authorizer: improv_authorizer

improv_serial:
